version: '3.9'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_blog_api
      MYSQL_USER: rails
      MYSQL_PASSWORD: rails_password

  web:
    build: .
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/var/www/my_blog_api
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data: